dataset_path: '/MLCV/haov/projects/video-sum/prompt_focus_vsum/eccv16_dataset_tvsum_google_pool5_sumprompt_clip_L14_useranno_virtualgt.h5'
split_path : '/MLCV/haov/projects/video-sum/tvsum_splits.json'


# model

vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
loss_type: 'cross_entropy'
tt_depth: 1
lambda_vsum: 1.0
kernel_size: 5
num_heads:  8
num_layers:  6

image_size: 224
max_video_length: 1294

# optimizer
init_lr: 1e-5
min_lr: 0
max_epoch: 300
batch_size: 1
weight_decay: 0.05

#save path 
save_dir : 'checkpoints'
